name: Docker Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 backend.store.conco store.conco admin.store.conco phpmyadmin.conco" | sudo tee -a /etc/hosts

      - name: Set env vars for frontend
        run: |
          echo ${{ secrets.VUE_APP_IMGBB_API_KEY }} | base64 -d > ./src/frontend/.env

      - name: Build containers
        run: |
          sudo chmod +x setup
          ./setup init

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          working-directory: ./app
          browser: chrome
          headless: true
          wait-on: "http://store.conco"
          project: ./src/cy-resources/
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
