name: Docker Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 backend.store.conco store.conco admin.store.conco phpmyadmin.conco" | sudo tee -a /etc/hosts

      - name: Set env vars for frontend
        run: |
          echo ${{ secrets.VUE_APP_IMGBB_API_KEY }} | base64 -d > ./src/frontend/.env

      - name: Build containers
        run: |
          echo "COMPOSE_PROJECT_NAME=online_store" > .env
          export $(echo ${{ secrets.CYPRESS_RECORD_KEY }} | base64 -d)
          docker compose -f docker-compose.yml -f docker-compose-x64.yml build
          docker compose -f docker-compose.yml run --rm --entrypoint="//opt/files/init" backend
          docker compose -f docker-compose.yml run --rm frontend yarn install
          docker compose -f docker-compose.yml -f docker-compose-x64.yml up --exit-code-from cypress-x64
