name: Docker Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v2

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 backend.store.conco store.conco admin.store.conco phpmyadmin.conco" | sudo tee -a /etc/hosts

      - name: Set env vars for frontend
        run: |
          touch ./src/frontend/.env
          echo ${{ secrets.VUE_APP_IMGBB_API_KEY }} > ./src/frontend/.env

      - name: Run initialize project script
        run: |
          sudo chmod +x setup
          ./setup init
      
      - name: Run tests
        run: |
          export $(echo ${{ secrets.CYPRESS_RECORD_KEY }} | base64 -d)
          docker compose -f docker-compose-x64.yml up --exit-code-from cypress-x64
